# precompiled header flags
IF(MSVC)
    # PCH_SOURCE_FILE
    # PCH_SOURCE_FILE_LIST
    # PCH_SOURCE_FILE_LIST_LEN
    # PCH_SOURCE_FILE_COMPILE_FLAG
    # PCH_SOURCE_FILE_PATH_COMPONENT
    FOREACH(PCH_SOURCE_FILE ${ID_SRCS})
        FILE(RELATIVE_PATH PCH_SOURCE_FILE ${CMAKE_CURRENT_SOURCE_DIR} ${PCH_SOURCE_FILE})
        
        SET(PCH_SOURCE_FILE_COMPILE_FLAG "/Yu")
        STRING(REPLACE "/" ";" PCH_SOURCE_FILE_LIST ${PCH_SOURCE_FILE})
        LIST(LENGTH PCH_SOURCE_FILE_LIST PCH_SOURCE_FILE_LIST_LEN)
        IF(${PCH_SOURCE_FILE_LIST_LEN} GREATER 1)
            MATH(EXPR PCH_SOURCE_FILE_LIST_LEN "${PCH_SOURCE_FILE_LIST_LEN} - 2")
            FOREACH(PCH_SOURCE_FILE_PATH_COMPONENT RANGE 0 ${PCH_SOURCE_FILE_LIST_LEN})
                SET(PCH_SOURCE_FILE_COMPILE_FLAG ${PCH_SOURCE_FILE_COMPILE_FLAG}../)
            ENDFOREACH(PCH_SOURCE_FILE_PATH_COMPONENT RANGE 0 ${PCH_SOURCE_FILE_LIST_LEN})
        ENDIF(${PCH_SOURCE_FILE_LIST_LEN} GREATER 1)

        IF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/precompiled.h)
            SET(PCH_SOURCE_FILE_COMPILE_FLAG ${PCH_SOURCE_FILE_COMPILE_FLAG}precompiled.h)
        ELSEIF(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/idlib/precompiled.h)
            SET(PCH_SOURCE_FILE_COMPILE_FLAG ${PCH_SOURCE_FILE_COMPILE_FLAG}idlib/precompiled.h)
        ELSEIF(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/../idlib/precompiled.h)
            SET(PCH_SOURCE_FILE_COMPILE_FLAG ${PCH_SOURCE_FILE_COMPILE_FLAG}../idlib/precompiled.h)
        ENDIF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/precompiled.h)

        #MESSAGE(STATUS ${PCH_SOURCE_FILE} ${PCH_SOURCE_FILE_COMPILE_FLAG})
        SET_SOURCE_FILES_PROPERTIES(${PCH_SOURCE_FILE} PROPERTIES COMPILE_FLAGS ${PCH_SOURCE_FILE_COMPILE_FLAG})
    ENDFOREACH(PCH_SOURCE_FILE ${ID_SRCS})

    IF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/precompiled.h)
        SET_SOURCE_FILES_PROPERTIES(precompiled.cpp PROPERTIES COMPILE_FLAGS "/Ycprecompiled.h")
    ELSEIF(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/idlib/precompiled.h)
        SET_SOURCE_FILES_PROPERTIES(precompiled.cpp PROPERTIES COMPILE_FLAGS "/Ycidlib/precompiled.h")
    ELSEIF(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/../idlib/precompiled.h)
        SET_SOURCE_FILES_PROPERTIES(precompiled.cpp PROPERTIES COMPILE_FLAGS "/Yc../idlib/precompiled.h")
    ENDIF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/precompiled.h)
ENDIF(MSVC)
