# precompiled header flags
IF(MSVC)
	IF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/precompiled.h)
		# PCH_SOURCE_FILE
		# PCH_SOURCE_FILE_LIST
		# PCH_SOURCE_FILE_LIST_LEN
		# PCH_SOURCE_FILE_COMPILE_FLAG		
		# PCH_SOURCE_FILE_PATH_COMPONENT
		FOREACH(PCH_SOURCE_FILE ${ID_SRCS})
			SET(PCH_SOURCE_FILE_COMPILE_FLAG "/Yu")
			STRING(REPLACE "/" ";" PCH_SOURCE_FILE_LIST ${PCH_SOURCE_FILE})
			LIST(LENGTH PCH_SOURCE_FILE_LIST PCH_SOURCE_FILE_LIST_LEN)
			IF(${PCH_SOURCE_FILE_LIST_LEN} GREATER 1)
				MATH(EXPR PCH_SOURCE_FILE_LIST_LEN "${PCH_SOURCE_FILE_LIST_LEN} - 2")
				FOREACH(PCH_SOURCE_FILE_PATH_COMPONENT RANGE 0 ${PCH_SOURCE_FILE_LIST_LEN})
					SET(PCH_SOURCE_FILE_COMPILE_FLAG ${PCH_SOURCE_FILE_COMPILE_FLAG}../)
				ENDFOREACH(PCH_SOURCE_FILE_PATH_COMPONENT RANGE 0 ${PCH_SOURCE_FILE_LIST_LEN})
			ENDIF(${PCH_SOURCE_FILE_LIST_LEN} GREATER 1)
			SET(PCH_SOURCE_FILE_COMPILE_FLAG ${PCH_SOURCE_FILE_COMPILE_FLAG}precompiled.h)
			#MESSAGE(STATUS ${PCH_SOURCE_FILE} ${PCH_SOURCE_FILE_COMPILE_FLAG})
			SET_SOURCE_FILES_PROPERTIES(${PCH_SOURCE_FILE} PROPERTIES COMPILE_FLAGS ${PCH_SOURCE_FILE_COMPILE_FLAG})
		ENDFOREACH(PCH_SOURCE_FILE ${ID_LIB_SRCS})
		SET_SOURCE_FILES_PROPERTIES(precompiled.cpp PROPERTIES COMPILE_FLAGS "/Ycprecompiled.h")
	ENDIF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/precompiled.h)
ENDIF(MSVC)
